# Dependencies
markdown:         kramdown
highlighter:      rouge

# Site settings
title: gotplot
description: >
  Various plots and charts in R by Gaston Sanchez
baseurl: "/gotplot"
url: "http://gastonsanchez.com/gotplot"

sass:
  style: compressed
